In [4]:
import gym_examples
import gym
import numpy as np
# from stable_baselines3 import PPO
import sb3_contrib as sb3
from sb3_contrib import MaskablePPO
from sb3_contrib.common.wrappers import ActionMasker
from sb3_contrib.common.maskable.policies import MaskableActorCriticPolicy
from gym.wrappers import FlattenObservation
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv
from sb3_contrib.common.maskable.utils import get_action_masks
from stable_baselines3.common.callbacks import EvalCallback
from stable_baselines3.common.callbacks import ProgressBarCallback
from stable_baselines3.common.vec_env import DummyVecEnv

In [5]:
sb3.__version__, gym.__version__
env_id = "gym_examples/CNN-v0"
model_save_path = "./logs/best_model"
log_path = "./logs"

# CNN ENV TESTING

In [3]:
env2 = gym.make("gym_examples/CNN-v0")

In [4]:
start_cnn = env2.reset()
start_cnn

({'layer_type': 0,
  'layer_depth': 0,
  'filter_depth': 0,
  'filter_size': 0,
  'fc_size': 0,
  'is_start': 1,
  'pool_size_and_stride': 0},
 {'current_network': [{'layer_type': 'conv',
    'layer_depth': 0,
    'filter_depth': 0,
    'filter_size': 0,
    'fc_size': 0,
    'image_size': 28,
    'pool_size': 0,
    'pool_stride': 0,
    'is_start': 1}],
  'current_image_size': 28,
  'current_layer_depth': 0,
  'current_num_fc_layers': 0,
  'obs_vector': array([0, 0, 0, 0, 0, 1, 0])})

In [5]:
env2.action_space

MultiDiscrete([3 9 5 4 5 2 4])

In [6]:
env2.get_valid_action_mask()

inside layer depth limit
enabling convolutions


(array([1, 0, 0], dtype=int8),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 1, 1, 1, 1], dtype=int8),
 array([0, 1, 1, 1], dtype=int8),
 array([1, 0, 0, 0, 0], dtype=int8),
 array([1, 0], dtype=int8),
 array([1, 0, 0, 0], dtype=int8))

In [7]:
env2.action_space.sample(mask=env2.get_valid_action_mask())

inside layer depth limit
enabling convolutions


array([0, 1, 4, 2, 0, 0, 0], dtype=int64)

In [7]:
# take an action that picks a conv layer, with 20 filters with a 3x3 kernel. 
action = np.array([0, 1, 2, 2, 0, 0, 0], dtype=np.int64)

new_obs, reward, terminated, _, info = env2.step(action)

inside layer depth limit
enabling convolutions
enabling valid pools


In [8]:
new_obs

{'layer_type': 0,
 'layer_depth': 1,
 'filter_depth': 2,
 'filter_size': 2,
 'fc_size': 0,
 'is_start': 0,
 'pool_size_and_stride': 0}

In [9]:
info

{'current_network': [{'layer_type': 'conv',
   'layer_depth': 0,
   'filter_depth': 0,
   'filter_size': 0,
   'fc_size': 0,
   'image_size': 28,
   'pool_size': 0,
   'pool_stride': 0,
   'is_start': 1},
  {'layer_type': 'conv',
   'layer_depth': 1,
   'filter_depth': 20,
   'filter_size': 3,
   'fc_size': 0,
   'image_size': 26,
   'is_start': 0,
   'pool_size': 0,
   'pool_stride': 0}],
 'current_image_size': 26,
 'current_layer_depth': 1,
 'current_num_fc_layers': 0,
 'obs_vector': array([0, 1, 2, 2, 0, 0, 0])}

In [11]:
env2.get_valid_action_mask()

inside layer depth limit
enabling convolutions
enabling valid pools


(array([1, 1, 1], dtype=int8),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int8),
 array([0, 1, 1, 1, 1], dtype=int8),
 array([0, 1, 1, 1], dtype=int8),
 array([0, 1, 1, 1, 1], dtype=int8),
 array([1, 1], dtype=int8),
 array([0, 1, 1, 1], dtype=int8))

In [12]:
#make an fc layer with 512
action = np.array([2, 2, 2, 2, 1, 0, 1], dtype=np.int64)
new_obs, reward, terminated, _, info = env2.step(action)

info

{'current_network': [{'layer_type': 'conv',
   'layer_depth': 0,
   'filter_depth': 0,
   'filter_size': 0,
   'fc_size': 0,
   'image_size': 28,
   'pool_size': 0,
   'pool_stride': 0,
   'is_start': 1},
  {'layer_type': 'conv',
   'layer_depth': 1,
   'filter_depth': 20,
   'filter_size': 3,
   'fc_size': 0,
   'image_size': 26,
   'is_start': 0,
   'pool_size': 0,
   'pool_stride': 0},
  {'layer_type': 'fc',
   'layer_depth': 2,
   'filter_depth': 20,
   'filter_size': 3,
   'fc_size': 512,
   'image_size': 26,
   'is_start': 0,
   'pool_size': 5,
   'pool_stride': 3}],
 'current_image_size': 26,
 'current_layer_depth': 2,
 'current_num_fc_layers': 1}

In [13]:
env2.get_valid_action_mask() #Only fc layer allowed and fc layer with less than 512 nodes and this has to be terminal layer

inside layer depth limit


(array([0, 0, 1], dtype=int8),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8),
 array([1, 0, 0, 0, 0], dtype=int8),
 array([1, 0, 0, 0], dtype=int8),
 array([0, 0, 1, 1, 1], dtype=int8),
 array([0, 1], dtype=int8),
 array([1, 0, 0, 0], dtype=int8))

In [14]:
action = np.array([2, 3, 0, 0, 2, 1, 0], dtype=np.int64)
new_obs, reward, terminated, _, info = env2.step(action)

info

network =  [{'layer_type': 'conv', 'layer_depth': 0, 'filter_depth': 0, 'filter_size': 0, 'fc_size': 0, 'image_size': 28, 'pool_size': 0, 'pool_stride': 0, 'is_start': 1}, {'layer_type': 'conv', 'layer_depth': 1, 'filter_depth': 20, 'filter_size': 3, 'fc_size': 0, 'image_size': 26, 'is_start': 0, 'pool_size': 0, 'pool_stride': 0}, {'layer_type': 'fc', 'layer_depth': 2, 'filter_depth': 20, 'filter_size': 3, 'fc_size': 512, 'image_size': 26, 'is_start': 0, 'pool_size': 5, 'pool_stride': 3}, {'layer_type': 'fc', 'layer_depth': 3, 'filter_depth': 0, 'filter_size': 0, 'fc_size': 256, 'image_size': 26, 'is_start': 0, 'pool_size': 0, 'pool_stride': 0}] terminated = True
layersList =  [('conv', 1, 20, 3, 1, 26, 0, 0, []), ('fc', 2, 20, 5, 3, 26, 512, 0, []), ('fc', 3, 0, 0, 0, 26, 256, 0, [])]


{'current_network': [{'layer_type': 'conv',
   'layer_depth': 0,
   'filter_depth': 0,
   'filter_size': 0,
   'fc_size': 0,
   'image_size': 28,
   'pool_size': 0,
   'pool_stride': 0,
   'is_start': 1},
  {'layer_type': 'conv',
   'layer_depth': 1,
   'filter_depth': 20,
   'filter_size': 3,
   'fc_size': 0,
   'image_size': 26,
   'is_start': 0,
   'pool_size': 0,
   'pool_stride': 0},
  {'layer_type': 'fc',
   'layer_depth': 2,
   'filter_depth': 20,
   'filter_size': 3,
   'fc_size': 512,
   'image_size': 26,
   'is_start': 0,
   'pool_size': 5,
   'pool_stride': 3},
  {'layer_type': 'fc',
   'layer_depth': 3,
   'filter_depth': 0,
   'filter_size': 0,
   'fc_size': 256,
   'image_size': 26,
   'is_start': 0,
   'pool_size': 0,
   'pool_stride': 0}],
 'current_image_size': 26,
 'current_layer_depth': 3,
 'current_num_fc_layers': 2}

In [15]:
reward

0.9907848744836352

In [5]:
# env = gym.make("gym_examples/StarWars-v0")

# PPO DEBUGGING

In [6]:
cnn_env = gym.make(env_id)
cnn_env.verbose = True

In [7]:
cnn_env.observation_space.sample()

OrderedDict([('fc_size', 2),
             ('filter_depth', 1),
             ('filter_size', 3),
             ('is_start', 0),
             ('layer_depth', 3),
             ('layer_type', 1),
             ('pool_size_and_stride', 0)])

In [8]:
eval_env = FlattenObservation(gym.make(env_id))
eval_env = DummyVecEnv([lambda: eval_env])

In [9]:
eval_callback = EvalCallback(eval_env, 
                             best_model_save_path=model_save_path, 
                             log_path=log_path, 
                             eval_freq=20, 
                             deterministic=True, 
                             render=False)

In [10]:
model = MaskablePPO(MaskableActorCriticPolicy, FlattenObservation(cnn_env), verbose=1)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [ ]:
model.learn(total_timesteps=100, callback=eval_callback, progress_bar=True)